version: '3.9'

services:
  runner:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules # prevent overriding node_modules with the ones from the host
      - ./output:/app/output
    working_dir: /app
    env_file:
      - .env
      - .env.local  # Higher priority
