version: '3.9'

services:
  browserless:
    image: browserless/chrome
    ports:
      - "3000:3000"
    environment:
      - PREBOOT_CHROME=true
      - ENABLE_DEBUGGER=true

  runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - browserless
    volumes:
      - .:/app
      - /app/node_modules # prevent overriding node_modules with the ones from the host
      - ./output:/app/output
    working_dir: /app
    env_file:
      - .env
      - .env.local  # Higher priority
